[package]
name = "mortgage_sim"
version = "0.1.0"
edition = "2024"
license = "MIT"

[profile.release]
lto = true
strip = true
opt-level = "s"

[dependencies]
csv = "1.4.0"
inquire = "0.9.1"
serde = { version = "1.0.228", features = ["serde_derive"] }
tabled = "0.20.0"
